lib/scentenced_web/router.ex
defmodule ScentencedWeb.Router do
  use ScentencedWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # If users maybe are logged in
  pipeline :auth do
    plug(Scentenced.Auth.AuthAccessPipeline)
  end

  # We use ensure_auth to fail if there is no one logged in
  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end


  scope "/", ScentencedWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/", ScentencedWeb do
    pipe_through [:browser, :auth]

    resources "/fragrant", FragrantController, only: [:index, :show]
    resources "/sessions", SessionController, only: [:delete]
    resources "/perfume", PerfumeController, only: [:index, :show]
    resources "/users", UserController, only: [:index, :show]
  end

  scope "/", ScentencedWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    resources "/fragrant", FragrantController
    resources "/sessions", SessionController, only: [:delete]
    resources "/perfume", PerfumeController
    resources "/users", UserController, only: [:index, :show]
  end


  # Other scopes may use custom stacks.
  # scope "/api", ScentencedWeb do
  #   pipe_through :api
  # end
end

lib/scentenced_web/views/layout_view.ex
defmodule ScentencedWeb.LayoutView do
  use ScentencedWeb, :view
end

lib/scentenced_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Scentenced</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <!-- Header -->
    <header>
      <nav class="navbar navbar-expand-sm fixed-top navbar-light bg-light">
        <a class="navbar-brand">
          <img
            src="<%= Routes.static_path(@conn, "/images/scentenced_logo.png") %>"
            alt="Scentenced Logo"
            height=30
          />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse" id="navbarNav" style>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="/fragrant">Fragrants</a></li>
            <li class="nav-item"><a class="nav-link" href="/perfume">Perfumes</a></li>
            <li class="nav-item"><%= link "Register", to: Routes.user_path(@conn, :new), class: "nav-link"  %></li>
            <li class="nav-item"><%= link "Login", to: Routes.session_path(@conn, :new), class: "nav-link"  %></li>
          </ul>
        </div>
      </nav>
    </header>

    <!-- Main -->
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/bootstrap.js") %>"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>